services:
  myrient-frontend:
    build: ./frontend
    container_name: myrient-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - myrient-backend
    networks:
      - myrient

  myrient-backend:
    build: ./backend
    container_name: myrient-backend
    restart: unless-stopped
    networks:
      - myrient

networks:
  myrient:
